import Footer from "@/components/pages/shared/Footer/Footer";
import Header from "@/components/pages/shared/Header/Header";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* header */}
        <Header />

        <main className="mt-[65px] xs:mt-[73px] md:mt-[81px] lg:mt-0">
          {children}
        </main>

        {/* footer */}
        <Footer />
      </body>
    </html>
  );
}
